src/Services/Masa.Scheduler.Services.Server/appsettings.Development.json, src/Services/Masa.Scheduler.Services.Server/appsettings.Staging.json, src/Services/Masa.Scheduler.Services.Server/appsettings.Testing.json, src/Services/Masa.Scheduler.Services.Server/appsettings.json, src/Services/Masa.Scheduler.Services.Worker/appsettings.Develop.json, src/Services/Masa.Scheduler.Services.Worker/appsettings.Staging.json, src/Services/Masa.Scheduler.Services.Worker/appsettings.Testing.json, src/Services/Masa.Scheduler.Services.Worker/appsettings.json, src/Web/Masa.Scheduler.Web.Admin.Server/appsettings.Develop.json, src/Web/Masa.Scheduler.Web.Admin.Server/appsettings.Staging.json, src/Web/Masa.Scheduler.Web.Admin.Server/appsettings.Testing.json
add staging and testing environment appsettings
=> chore: add staging and testing environment appsettings

src/Contracts/Masa.Scheduler.Contracts.Server/Infrastructure/Managers/BaseSchedulerManager.cs, src/Services/Masa.Scheduler.Services.Server/appsettings.Staging.json, src/Services/Masa.Scheduler.Services.Server/appsettings.Testing.json, src/Services/Masa.Scheduler.Services.Worker/appsettings.Staging.json, src/Services/Masa.Scheduler.Services.Worker/appsettings.Testing.json
when only register https or http,  server or worker cannot register each other
=> fix: fix monitor online bug

src/Contracts/Masa.Scheduler.Contracts.Server/Infrastructure/Managers/BaseSchedulerManager.cs, src/Services/Masa.Scheduler.Services.Server/Application/Auths/AuthQueryHandler.cs, src/Services/Masa.Scheduler.Services.Server/Domain/Managers/Servers/SchedulerServerManager.cs, src/Services/Masa.Scheduler.Services.Worker/Domain/Managers/Workers/SchedulerWorkerManager.cs
fix send online request before consume queue
=> fix: send online request

src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/Masa.Scheduler.ApiGateways.Caller.csproj, src/Contracts/Masa.Scheduler.Contracts.Server/Masa.Scheduler.Contracts.Server.csproj, src/Services/Masa.Scheduler.Services.Server/Application/Jobs/SchedulerJobCommandHandler.cs, src/Services/Masa.Scheduler.Services.Server/Application/Jobs/SchedulerJobQueryHandler.cs, src/Services/Masa.Scheduler.Services.Server/Masa.Scheduler.Services.Server.csproj, src/Services/Masa.Scheduler.Services.Server/appsettings.Develop.json, src/Services/Masa.Scheduler.Services.Server/appsettings.Development.json, src/Services/Masa.Scheduler.Services.Server/appsettings.Staging.json, src/Services/Masa.Scheduler.Services.Worker/Masa.Scheduler.Services.Worker.csproj, src/Services/Masa.Scheduler.Services.Worker/appsettings.Develop.json, src/Services/Masa.Scheduler.Services.Worker/appsettings.Development.json, src/Services/Masa.Scheduler.Services.Worker/appsettings.Staging.json, src/Services/Masa.Scheduler.Services.Worker/appsettings.json, src/Shells/Masa.Scheduler.Shells.JobShell/Masa.Scheduler.Shells.JobShell.csproj, src/Web/Masa.Scheduler.Web.Admin.Server/appsettings.Develop.json, src/Web/Masa.Scheduler.Web.Admin.Server/appsettings.Development.json, src/Web/Masa.Scheduler.Web.Admin.Server/appsettings.Staging.json, src/Web/Masa.Scheduler.Web.Admin.Server/appsettings.json, src/Web/Masa.Scheduler.Web.Admin/Masa.Scheduler.Web.Admin.csproj, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/JobModal.razor.cs, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor.cs, src/Web/Masa.Scheduler.Web.Admin/wwwroot/i18n/en-US.json, src/Web/Masa.Scheduler.Web.Admin/wwwroot/i18n/zh-CN.json
1. upgrade masa framework packages 
2. modify OTLP config
=> chore: upgrade masa framework packages 

Directory.Build.props, src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/Masa.Scheduler.ApiGateways.Caller.csproj, src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/SchedulerServerCaller.cs, src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/_Imports.cs, src/Services/Masa.Scheduler.Services.Server/Program.cs, src/Services/Masa.Scheduler.Services.Server/_Imports.cs, src/Web/Masa.Scheduler.Web.Admin.Server/_Imports.cs, src/Web/Masa.Scheduler.Web.Admin/Masa.Scheduler.Web.Admin.csproj, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Team.razor, src/Web/Masa.Scheduler.Web.Admin/Shared/MainLayout.razor, src/Web/Masa.Scheduler.Web.Admin/_Imports.razor
1. fix：Handling global team switching and server carrying token processing
2. chore : update masa nuget package
=> fix：Handle global team switch and update masa package

.gitignore, src/Contracts/Masa.Scheduler.Contracts.Server/Infrastructure/Extensions/DnsHelper.cs, src/Contracts/Masa.Scheduler.Contracts.Server/Infrastructure/Managers/BaseSchedulerManager.cs, src/Services/Masa.Scheduler.Services.Server/Application/Jobs/Queries/SchedulerJobQueryByIdentity.cs, src/Services/Masa.Scheduler.Services.Worker/Services/SchedulerWorkerManagerService.cs, src/Web/Masa.Scheduler.Web.Admin/Pages/SchedulerResources/SchedulerResourceFiles.razor.cs
style: Delete Job popover style and text adjustment
1. ignore the exception and use Dns.GetHostName() directly
2. ignore .idea, .DS_Store for source manage
3. delete Job popover style and text adjustment
=> style: Delete Job popover style and text adjustment

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerTasks.razor
=> fix:The restart task and Interrupt task buttons are missing ICONS

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Team.razor
=> fix:The scroll bar to the right of the project team page has been removed, resolve (#168)

Directory.Build.props, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/JobModal.razor
=> fix:Edit the Job page icon offset

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/JobModal.razor
_Please explain the changes you've made_
=> feat:Whether the alarm button is blocked

src/Web/Masa.Scheduler.Web.Admin.Server/Pages/_Layout.cshtml, src/Web/Masa.Scheduler.Web.Admin/Pages/SchedulerResources/Components/SchedulerResourceFilesInformation.razor.cs, src/Web/Masa.Scheduler.Web.Admin/wwwroot/js/download-file.js
=> fix:The file name is changed after the file is downloaded. resolve #138

src/Web/Masa.Scheduler.Web.Admin/Pages/SchedulerResources/Components/AddSchedulerResourceFiles.razor, src/Web/Masa.Scheduler.Web.Admin/wwwroot/i18n/en-US.json
=> fix:File uploaded successfully style adjustment. resolve #173

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor
_Please explain the changes you've made_
=> feat:update schedulerjobs css

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor
=> Fix issues 0190

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor
=> fix:When the person in charge of a Job is empty, the person in charge is blank

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/JobModal.razor, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/JobModal.razor.cs
=> fix:Form validation should occur when an action is triggered.resolved #245

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor.cs, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerTasks.razor, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerTasks.razor.cs, src/Web/Masa.Scheduler.Web.Admin/wwwroot/css/masa-scheduler.css, src/Web/Masa.Scheduler.Web.Admin/wwwroot/i18n/zh-CN.json
_1.Fix job query type list
2.datetimerangepicker style change to min-width,  because the text in the small screen overlaps
3.Change the Chinese datetime format_
* [√] Code compiles correctly
=> Fix job query type list, datetimerangepicker style change to min-width

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor.cs, src/Web/Masa.Scheduler.Web.Admin/_Imports.cs, src/Web/Masa.Scheduler.Web.Admin/wwwroot/i18n/en-US.json, src/Web/Masa.Scheduler.Web.Admin/wwwroot/i18n/zh-CN.json
时间显示正常，23小时不会再显示昨天（yesterday），而是正常显示23小时以前
=> fix:The Cron expression ran the Job. The task completion time was incorrect. Procedure，resolved #255

src/Web/Masa.Scheduler.Web.Admin/Pages/SchedulerResources/SchedulerResourceFiles.razor.cs, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor.cs, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerTasks.razor.cs
_Loading does not close without called async function_
* [√] Code compiles correctly
=> Fix: Loading does not close without called async function

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor.cs
1. reset all fiter after select new project
2. remove unused code
resovel  #316
=> fix: reset all fiter after select new project

src/Web/Masa.Scheduler.Web.Admin/Components/AlarmRules/AlarmRuleSetting.razor, src/Web/Masa.Scheduler.Web.Admin/Components/AlarmRules/LogAlarmRuleUpsertModal.razor, src/Web/Masa.Scheduler.Web.Admin/Components/AlarmRules/LogAlarmRuleUpsertModal.razor.cs, src/Web/Masa.Scheduler.Web.Admin/Components/DateTimeFormat.razor, src/Web/Masa.Scheduler.Web.Admin/Components/Notification/NotificationConfig.razor, src/Web/Masa.Scheduler.Web.Admin/Components/Pickers/DateTimeRangePicker.razor, src/Web/Masa.Scheduler.Web.Admin/Components/Subjects/UserAutoComplete.razor, src/Web/Masa.Scheduler.Web.Admin/Components/Subjects/UserAutoComplete.razor.cs, src/Web/Masa.Scheduler.Web.Admin/Pages/SchedulerResources/Components/AddSchedulerResourceFiles.razor, src/Web/Masa.Scheduler.Web.Admin/Pages/SchedulerResources/Components/SchedulerResourceFilesInformation.razor, src/Web/Masa.Scheduler.Web.Admin/Pages/SchedulerResources/SchedulerResourceFiles.razor, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/JobModal.razor, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/Projects.razor, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor.cs, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerTasks.razor, src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Team.razor, src/Web/Masa.Scheduler.Web.Admin/Shared/MainLayout.razor, src/Web/Masa.Scheduler.Web.Admin/Shared/ProComponentBase.cs
fix name `ProCompontentBase` to `ProComponentBase`
=> fix: ProCompontentBase to ProComponentBase

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerTasks.razor
=> fix:Job detail page navigation show error. resolved #269

src/Web/Masa.Scheduler.Web.Admin/Components/DateTimeFormat.razor.cs, src/Web/Masa.Scheduler.Web.Admin/Masa.Scheduler.Web.Admin.csproj
Fixing the spelling of method names
update nuget package version
=> chore: Fixing the spelling of method names,update nuget package version

src/Web/Masa.Scheduler.Web.Admin/Masa.Scheduler.Web.Admin.csproj
_Please explain the changes you've made_
=> feat:update package

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobs.razor
_Please explain the changes you've made_
=> fix:icon+ text buttons, ICONS don't need tooltips

src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerTasks.razor
https://github.com/masastack/MASA.TSC/pull/435
=> fix: update tsc url

src/Services/Masa.Scheduler.Services.Worker/Domain/Managers/Workers/SchedulerWorkerManager.cs
https://github.com/masastack/MASA.Scheduler/issues/455
=> fix : issues 455

.gitlab-ci.yml
=> ci：update gitlab-ci

src/Services/Masa.Scheduler.Services.Server/Domain/Managers/Servers/ServerScopedProcessingService.cs
Add a try catch block in ServerScopedProcessingService, Capture exceptions in scope creation and task execution, and record error logs, Ensure that background tasks can continue to run without interruption in case of errors. Keep the original function logic, and optimize the code structure to improve robustness.
=> fix: Enhance exception handling and fault tolerance of background tasks
